export const ERROR_MESSAGES = {
  NO_REMAIN_SEATS: '좌석이 다 찼어요 :(',
  DUPLICATE_APPLICATION_EVENT: '이미 신청하셨어요 :)',
  TIME_ERROR: '시간을 다시 확인해주세요',
  MENTOR_ALREADY_APPROVED: '이미 승인된 멘토에요',
  INFO_NOT_FOUND: '임시 정보를 찾지 못했어요',
  MENTEE_NOT_FOUND: '멘티를 찾을 수 없어요 :(',
  DUPLICATED_EVENT_OPEN: '이미 오픈된 이벤트가 있어요',
  NO_AVAILABLE_SEATS: '잔여 자리가 없어요 :(',
  SERVER_ERROR: '서버에 문제가 있어요 :(',
  NOT_OPEN_TIME: '아직 오픈 시간이 아니에요',
  EVENT_REJECTED: '이벤트가 거절되었어요 :(',
  RANGE_MAXIMUM_ATTENDEE: '인원은 2~10명으로 해주세요',
  RESUME_NOT_FOUND: '이력서를 찾을 수 없어요',
  MENTEE_ONLY_RESUME: '멘티만 이력서를 쓸 수 있어요',
  INVALID_ACCESS_TOKEN: '액세스 토큰이 유효하지 않아요',
  BAD_REQUEST: '요청이 잘못됐어요 :(',
  PROJECT_NOT_FOUND: '프로젝트를 찾지 못했어요',
  ROLE_NOT_ALLOWED: '역할이 허용되지 않아요',
  LOGIN_REQUIRED: '로그인이 필요해요 :)',
  APPLICATION_NOT_FOUND: '예약 이력을 찾을 수 없어요',
  NO_EMPTY_VALUE: '값이 비어있으면 안 돼요',
  EVENT_NOT_FOUND: '이벤트를 찾을 수 없어요',
  APPLICANT_NOT_FOUND: '신청 이력이 없어요 :(',
  CAN_NOT_RESERVATION: '이전 시간으로 예약은 안 돼요',
  COMPONENT_NOT_FOUND: '이력서 블록이 없어요 :(',
  CANNOT_OPEN_EVENT: '예약 이벤트만 신청 가능해요',
  GPA_ERROR: '최대 학점은 내 학점보다 커야 해요',
  MENTOR_NOT_FOUND: '멘토를 찾을 수 없어요 :(',
};
