export const ERROR_MESSAGES = {
  NO_REMAIN_SEATS: '인원이 다 찼어요 :(',
  DUPLICATE_APPLICATION_EVENT: '한 번에 한개의 이벤트만 신청할 수 있어요. :)',
  TIME_ERROR: '시작일은 종료일보다 빨라야 해요.',
  INFO_NOT_FOUND: '회원 가입 시간이 초과 되었어요.',
  DUPLICATED_EVENT_OPEN: '이미 오픈된 이벤트가 있어요.',
  SERVER_ERROR: '서버에 문제가 있어요 :(',
  NOT_OPEN_TIME: '아직 오픈 시간이 아니에요',
  EVENT_REJECTED: '피드백 신청이 거절되었어요 :(',
  RANGE_MAXIMUM_ATTENDEE: '인원은 2~10명으로 해주세요',
  RESUME_NOT_FOUND: '이력서를 찾을 수 없어요. :(',
  INVALID_ACCESS_TOKEN: '액세스 토큰이 유효하지 않아요.',
  LOGIN_REQUIRED: '로그인이 필요해요 :)',
  EVENT_NOT_FOUND: '이벤트를 찾을 수 없어요. :(',
  CAN_NOT_RESERVATION: '신청 시작 시간을 현재시간 이후로 설정해주세요.',
  GPA_ERROR: '최대 학점은 내 학점보다 커야 해요',
  MENTOR_NOT_FOUND: '멘토를 찾을 수 없어요 :(',
  NOT_UPDATE_EVENT: '모집 받는 중에는 수정할 수 없어요.',
};
